#!/usr/bin/env node
// Bundle activities.json + tracks.json into a single front-end data file (data.js).
import { readFileSync, writeFileSync } from "node:fs";

const ROOT = process.argv[2] ?? ".";
const activities = JSON.parse(readFileSync(`${ROOT}/activities.json`, "utf8"));
const tracks = JSON.parse(readFileSync(`${ROOT}/tools/tracks.json`, "utf8")).tracks;
const health = JSON.parse(readFileSync(`${ROOT}/tools/health.json`, "utf8"));

const bundle = {
  generated: new Date().toISOString(),
  activities,
  tracks,
  health,
};

const out = `// Auto-generated by tools/generate_data.mjs — do not edit by hand.\nwindow.RUN_DATA = ${JSON.stringify(bundle)};\n`;
writeFileSync(`${ROOT}/data.js`, out, "utf8");

const size = Buffer.byteLength(out, "utf8");
console.log(`wrote data.js: ${activities.length} activities, ${Object.keys(tracks).length} tracks, ${(size / 1024).toFixed(1)} KB`);
